# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: public.ecr.aws/cilantro/cray-workloads:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://raw.githubusercontent.com/romilbhardwaj/cilantro-workloads/main/cray_workloads/k8s/playground/print_clusterstats.py &&
              python print_clusterstats.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
